name: Fetch Data and Push Changes

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour at the top of the hour

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests sqlite3

    - name: Run script
      env:
        API_KEY: ${{ secrets.API_KEY }}  # Use GitHub Secret for API key
      run: |
        python fetch_data.py

    - name: Commit changes to data.db
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data.db
        git commit -m "Update data.db with new data"
      continue-on-error: true  # Continue even if no changes (no commit needed)

    - name: Push changes back to repository
      uses: ad-m/github-push-action@v1  # Using an action to push back changes
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub Actions token
